### ISSUE TITLE
PCSpec 클래스의 멤버 변수는 필수 값인데 빌더에서는 선택 값으로 입력받고 있습니다.

### ISSUE THREAD

**Issue by swsz2** [lgm1007/effective-java#1]
PCSpec 클래스의 멤버 변수는 필수값인데 빌더에서는 선택값으로 입력받고 있습니다.
의도하지 않은 버그가 발생할 수 있는 구성인 거 같습니다.

[PCSpec.java](https://github.com/lgm1007/effective-java/blob/master/src/main/com/lgm/study/chapter2/act2/PCSpec.java)
[PCSpecTest.java](https://github.com/lgm1007/effective-java/blob/master/src/test/com/lgm/study/chapter2/act2/PCSpecTest.java)

**Comment by swsz2** [comment]
아래와 같이 개선하는 것은 어떨까요?

1. PC 사양에 하한선을 두고 싶다 : 필드에 기본값을 준다.
2. 모든 사양을 꼭 입력 받고 싶다 : 빌더 생성자에서 모든 사양을 매개변수로 입력받는다.
3. 일부 사양만 입력 받고 싶다 : 필수 사양만 빌더 생성자에서 매개변수로 입력받는다.

**Comment by lgm1007** [comment]
말씀해주신 사항들은 확실히 버그가 발생할 수 있는 부분이었던 것 같습니다.
말씀해주신 개선 방향 중 클래스를 추가하여 2가지 방식으로 개선 진행하였습니다.

1. PC 사양에 하한선을 두기
2. 필수 사양을 빌더 생성자에서 매개변수로 입력받기

[Commit dd9c5b0](https://github.com/lgm1007/effective-java/commit/dd9c5b0938019930e1bdd9e0f89aa9a0e33edbb0)

**Comment by swsz2** [comment]
오호 수정하셨네요

만약 저였다면 저는 PC 사양 하한선을 주기 위해서 PCSpecType1  클래스에 기본값을 주는 것이 아닌 빌더에 줬을 거 같아요.
아무래도 PCSpecType1 클래스에 두게 되면 추후 멤버 변수의 값이 변경될 수 있는 여지가 생길 거 같아서요

어찌됐든 그건 객체 설계에 대한 내용이고 버그가 발생할 수 있는 부분은 수정된 거 같네요!

해당 이슈는 닫아도 될 거 같아요
